param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$TestProject = "C:\Users\Dario Costa\Desktop\projects\castrosua_legacy\test_project",
  [int]$ScrollSteps = 8,
  [switch]$PrepareRunDir,
  [switch]$KeepOpen,
  [switch]$NoKillExisting,
  [switch]$AllowWarp
)

$ErrorActionPreference = "Stop"

function Invoke-Msys([string]$Command) {
  $bash = "C:\msys64\usr\bin\bash.exe"
  if (!(Test-Path $bash)) { throw "MSYS2 bash not found: $bash" }
  & $bash -lc "export MSYSTEM=MINGW64; export PATH=/mingw64/bin:/usr/bin:/bin:`$PATH; $Command"
  if ($LASTEXITCODE -ne 0) { throw "MSYS command failed with exit code $LASTEXITCODE" }
}

function Prepare-RunDirectory([string]$RepoRoot) {
  $repoMsys = $RepoRoot -replace '^([A-Za-z]):', '/$1' -replace '\\', '/'
  $repoMsys = $repoMsys.ToLowerInvariant()
  Invoke-Msys @"
cd '$repoMsys' && \
meson compile -C build-windows-x86_64 && \
rm -rf .run && \
mkdir -p .run/bin .run/share/anvil .run/share/anvil/core && \
cp build-windows-x86_64/src/anvil.exe .run/bin/ && \
for module_name in core compat plugins colors fonts; do cp -r data/`$module_name .run/share/anvil/; done && \
if [ -d subprojects/widget ]; then cp -a subprojects/widget .run/share/anvil/; fi && \
if [ -d subprojects/colors ]; then cp -a subprojects/colors/colors .run/share/anvil/colors; fi && \
if [ -d subprojects/plugins ]; then cp -a subprojects/plugins/plugins/language_* .run/share/anvil/plugins/ 2>/dev/null || true; fi && \
cp build-windows-x86_64/start.lua .run/share/anvil/core/
"@
}

function New-ScrollFixture([string]$TestProject) {
  New-Item -ItemType Directory -Force -Path $TestProject | Out-Null
  $projectConfig = Join-Path $TestProject ".anvil_project.lua"
  @'
local config = require "core.config"
config.plugins.editor_wallpaper = false
config.plugins.custom_welcome = false
config.plugins.ipc = false
config.plugins.workspace = false
'@ | Set-Content -LiteralPath $projectConfig -Encoding UTF8
  $fixture = Join-Path $TestProject "render_scroll_fixture.txt"
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("Anvil D3D11 renderer smoke fixture")
  $lines.Add("Generated by scripts/d3d11-smoke-test.ps1")
  $lines.Add("")
  for ($i = 1; $i -le 3000; $i++) {
    $prefix = "{0:D4}" -f $i
    $text = "function render_test_${prefix}() -- tabs`tunicode OK punctuation []{}<> long-long-long-long-long-long-long-long-long-long"
    $lines.Add("${prefix}  $text")
  }
  Set-Content -LiteralPath $fixture -Value $lines -Encoding UTF8
  return $fixture
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type @"
using System;
using System.Runtime.InteropServices;
public static class AnvilSmokeWin32 {
  [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }
  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
  [DllImport("user32.dll")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT rect);
  [DllImport("user32.dll")] public static extern bool PrintWindow(IntPtr hWnd, IntPtr hdcBlt, uint nFlags);
  [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr hWnd, uint Msg, IntPtr wParam, IntPtr lParam);
}
"@

function Wait-MainWindow([System.Diagnostics.Process]$Process, [int]$TimeoutMs = 10000) {
  $deadline = [Environment]::TickCount + $TimeoutMs
  do {
    Start-Sleep -Milliseconds 100
    $Process.Refresh()
    if ($Process.HasExited) { throw "Anvil exited before creating a main window" }
    if ($Process.MainWindowHandle -ne [IntPtr]::Zero) { return ([IntPtr]$Process.MainWindowHandle) }
  } while ([Environment]::TickCount -lt $deadline -and !$Process.HasExited)
  throw "Timed out waiting for Anvil main window"
}

function Capture-Window([IntPtr]$Hwnd, [string]$Path) {
  [AnvilSmokeWin32]::ShowWindow($Hwnd, 5) | Out-Null
  [AnvilSmokeWin32]::SetForegroundWindow($Hwnd) | Out-Null
  Start-Sleep -Milliseconds 250
  $rect = New-Object AnvilSmokeWin32+RECT
  if (![AnvilSmokeWin32]::GetWindowRect($Hwnd, [ref]$rect)) { throw "GetWindowRect failed" }
  $width = [Math]::Max(1, $rect.Right - $rect.Left)
  $height = [Math]::Max(1, $rect.Bottom - $rect.Top)
  $bmp = New-Object System.Drawing.Bitmap $width, $height
  $gfx = [System.Drawing.Graphics]::FromImage($bmp)
  try {
    $printed = $false
    $hdc = $gfx.GetHdc()
    try {
      $printed = [AnvilSmokeWin32]::PrintWindow($Hwnd, $hdc, 2)
    } finally {
      $gfx.ReleaseHdc($hdc)
    }
    if (!$printed) {
      $gfx.CopyFromScreen($rect.Left, $rect.Top, 0, 0, $bmp.Size)
    }
    $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
  } finally {
    $gfx.Dispose()
    $bmp.Dispose()
  }
}

function Get-FileSha256([string]$Path) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  $stream = [System.IO.File]::OpenRead($Path)
  try {
    $hash = $sha.ComputeHash($stream)
    return -join ($hash | ForEach-Object { $_.ToString("x2") })
  } finally {
    $stream.Dispose()
    $sha.Dispose()
  }
}

function Quote-CommandLineArg([string]$Arg) {
  return '"' + ($Arg -replace '"', '\"') + '"'
}

function Start-AnvilProcess([string]$Exe, [string]$Fixture, [string]$WorkingDirectory) {
  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $Exe
  $psi.WorkingDirectory = $WorkingDirectory
  $psi.UseShellExecute = $false
  $psi.Arguments = "edit " + (Quote-CommandLineArg $Fixture)
  return [System.Diagnostics.Process]::Start($psi)
}

if (!$NoKillExisting) {
  Get-Process anvil -ErrorAction SilentlyContinue | Stop-Process -Force
  Start-Sleep -Milliseconds 300
}

if ($PrepareRunDir) { Prepare-RunDirectory $RepoRoot }

$runDir = Join-Path $RepoRoot ".run"
$exe = Join-Path $runDir "bin\anvil.exe"
if (!(Test-Path $exe)) {
  throw "Run-local executable not found: $exe. Re-run with -PrepareRunDir."
}

# Make screenshots deterministic and text-focused. The source tree defaults are
# untouched; this only edits the ignored .run copy prepared for the smoke test.
$defaultsCopy = Join-Path $runDir "share\anvil\plugins\anvil_defaults.lua"
if (Test-Path $defaultsCopy) {
  $defaultsText = Get-Content -LiteralPath $defaultsCopy -Raw
  $defaultsText = $defaultsText.Replace('require "plugins.editor_wallpaper"', '-- smoke-test disabled: require "plugins.editor_wallpaper"')
  $defaultsText = $defaultsText.Replace('require "plugins.custom_welcome"', '-- smoke-test disabled: require "plugins.custom_welcome"')
  Set-Content -LiteralPath $defaultsCopy -Value $defaultsText -Encoding UTF8
}

$fixture = New-ScrollFixture $TestProject
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$outDir = Join-Path $TestProject "anvil-d3d11-smoke-$stamp"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$statsFile = Join-Path $outDir "d3d11-stats.csv"

$oldUserProfile = $env:USERPROFILE
$oldUserDir = $env:ANVIL_USERDIR
$oldRenderer = $env:ANVIL_RENDERER
$oldStats = $env:ANVIL_D3D11_STATS
$oldStatsFile = $env:ANVIL_D3D11_STATS_FILE
$oldStatsFlush = $env:ANVIL_D3D11_STATS_FLUSH
$proc = $null
try {
  $smokeUserDir = Join-Path $runDir ".config\anvil"
  New-Item -ItemType Directory -Force -Path $smokeUserDir | Out-Null
  $env:USERPROFILE = $runDir
  $env:ANVIL_USERDIR = $smokeUserDir
  $env:ANVIL_RENDERER = "d3d11"
  $env:ANVIL_D3D11_STATS = "1"
  $env:ANVIL_D3D11_STATS_FLUSH = "1"
  $env:ANVIL_D3D11_STATS_FILE = $statsFile

  Remove-Item -LiteralPath (Join-Path $smokeUserDir "session.lua") -Force -ErrorAction SilentlyContinue
  $proc = Start-AnvilProcess $exe $fixture $TestProject
  $hwnd = Wait-MainWindow $proc
  Start-Sleep -Seconds 2
  $captures = New-Object System.Collections.Generic.List[string]
  $openCapture = Join-Path $outDir "00-open.png"
  Capture-Window $hwnd $openCapture
  $captures.Add($openCapture) | Out-Null

  for ($i = 1; $i -le $ScrollSteps; $i++) {
    [AnvilSmokeWin32]::SetForegroundWindow($hwnd) | Out-Null
    $rect = New-Object AnvilSmokeWin32+RECT
    [AnvilSmokeWin32]::GetWindowRect($hwnd, [ref]$rect) | Out-Null
    $mx = [int](($rect.Left + $rect.Right) / 2)
    $my = [int](($rect.Top + $rect.Bottom) / 2)
    $lp = (($my -band 0xffff) -shl 16) -bor ($mx -band 0xffff)
    [AnvilSmokeWin32]::PostMessage($hwnd, 0x020A, [IntPtr](-7864320), [IntPtr]$lp) | Out-Null
    [AnvilSmokeWin32]::PostMessage($hwnd, 0x0100, [IntPtr]0x22, [IntPtr]0) | Out-Null
    [AnvilSmokeWin32]::PostMessage($hwnd, 0x0101, [IntPtr]0x22, [IntPtr]0) | Out-Null
    Start-Sleep -Milliseconds 180
    if ($i -eq 1 -or $i -eq $ScrollSteps -or ($i % 4) -eq 0) {
      $capture = Join-Path $outDir ("{0:D2}-scroll.png" -f $i)
      Capture-Window $hwnd $capture
      $captures.Add($capture) | Out-Null
    }
  }

  Start-Sleep -Milliseconds 500
  if (!(Test-Path $statsFile)) {
    throw "Stats file was not created: $statsFile"
  }
  Get-Content -LiteralPath $statsFile -Head 8 | Out-Host
  $statsRows = @(Import-Csv -LiteralPath $statsFile)
  if ($statsRows.Count -lt 1) { throw "Stats file contains no frames: $statsFile" }
  $latestStats = $statsRows[$statsRows.Count - 1]
  if ($latestStats.path -ne "commands" -or $latestStats.success -ne "1") {
    throw "D3D11 command renderer did not complete the latest frame successfully"
  }
  if (!$AllowWarp -and $latestStats.device -ne "hardware") {
    throw "D3D11 smoke expected hardware device, got '$($latestStats.device)'"
  }
  Write-Host ("D3D11 summary: frame={0} device={1} adapter={2} draw_calls={3} quad_instances={4}" -f $latestStats.frame, $latestStats.device, $latestStats.adapter, $latestStats.draw_calls, $latestStats.quad_instances)

  $hashes = @($captures | ForEach-Object { Get-FileSha256 $_ })
  $uniqueHashes = @($hashes | Select-Object -Unique)
  Write-Host ("Screenshot hashes: {0} unique of {1}" -f $uniqueHashes.Count, $hashes.Count)
  if ($ScrollSteps -gt 0 -and $uniqueHashes.Count -lt 2) {
    throw "Scroll validation failed: captured screenshots are identical"
  }

  Write-Host "Smoke output: $outDir"
} finally {
  if ($proc -and !$KeepOpen) {
    try {
      $proc.Refresh()
      if (!$proc.HasExited) {
        $proc.CloseMainWindow() | Out-Null
        if (!$proc.WaitForExit(3000)) { $proc.Kill() }
      }
    } catch {
      try { if ($proc -and !$proc.HasExited) { $proc.Kill() } } catch {}
    }
  }
  $env:USERPROFILE = $oldUserProfile
  $env:ANVIL_USERDIR = $oldUserDir
  $env:ANVIL_RENDERER = $oldRenderer
  $env:ANVIL_D3D11_STATS = $oldStats
  $env:ANVIL_D3D11_STATS_FILE = $oldStatsFile
  $env:ANVIL_D3D11_STATS_FLUSH = $oldStatsFlush
}
