param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
  [string]$TestProject = "C:\Users\Dario Costa\Desktop\projects\castrosua_legacy\test_project",
  [int]$ScrollSteps = 8,
  [switch]$PrepareRunDir,
  [switch]$KeepOpen,
  [switch]$NoKillExisting
)

$ErrorActionPreference = "Stop"

function Invoke-Msys([string]$Command) {
  $bash = "C:\msys64\usr\bin\bash.exe"
  if (!(Test-Path $bash)) { throw "MSYS2 bash not found: $bash" }
  & $bash -lc "export MSYSTEM=MINGW64; export PATH=/mingw64/bin:/usr/bin:/bin:`$PATH; $Command"
  if ($LASTEXITCODE -ne 0) { throw "MSYS command failed with exit code $LASTEXITCODE" }
}

function Prepare-RunDirectory([string]$RepoRoot) {
  $repoMsys = $RepoRoot -replace '^([A-Za-z]):', '/$1' -replace '\\', '/'
  $repoMsys = $repoMsys.ToLowerInvariant()
  Invoke-Msys @"
cd '$repoMsys' && \
meson compile -C build-windows-x86_64 && \
rm -rf .run && \
mkdir -p .run/bin .run/share/anvil .run/share/anvil/core && \
cp build-windows-x86_64/src/anvil.exe .run/bin/ && \
for module_name in core compat plugins colors fonts; do cp -r data/`$module_name .run/share/anvil/; done && \
if [ -d subprojects/widget ]; then cp -a subprojects/widget .run/share/anvil/; fi && \
if [ -d subprojects/colors ]; then cp -a subprojects/colors/colors .run/share/anvil/colors; fi && \
if [ -d subprojects/plugins ]; then cp -a subprojects/plugins/plugins/language_* .run/share/anvil/plugins/ 2>/dev/null || true; fi && \
cp build-windows-x86_64/start.lua .run/share/anvil/core/
"@
}

function New-ScrollFixture([string]$TestProject) {
  New-Item -ItemType Directory -Force -Path $TestProject | Out-Null
  $fixture = Join-Path $TestProject "render_scroll_fixture.txt"
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("Anvil D3D11 renderer smoke fixture")
  $lines.Add("Generated by scripts/d3d11-smoke-test.ps1")
  $lines.Add("")
  for ($i = 1; $i -le 3000; $i++) {
    $prefix = "{0:D4}" -f $i
    $text = "function render_test_${prefix}() -- tabs`tunicode OK punctuation []{}<> long-long-long-long-long-long-long-long-long-long"
    $lines.Add("${prefix}  $text")
  }
  Set-Content -LiteralPath $fixture -Value $lines -Encoding UTF8
  return $fixture
}

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type @"
using System;
using System.Runtime.InteropServices;
public static class AnvilSmokeWin32 {
  [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }
  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
  [DllImport("user32.dll")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT rect);
  [DllImport("user32.dll")] public static extern bool PrintWindow(IntPtr hWnd, IntPtr hdcBlt, uint nFlags);
  [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr hWnd, uint Msg, IntPtr wParam, IntPtr lParam);
}
"@

function Wait-MainWindow([System.Diagnostics.Process]$Process, [int]$TimeoutMs = 10000) {
  $deadline = [Environment]::TickCount + $TimeoutMs
  do {
    Start-Sleep -Milliseconds 100
    $Process.Refresh()
    if ($Process.HasExited) { throw "Anvil exited before creating a main window" }
    if ($Process.MainWindowHandle -ne [IntPtr]::Zero) { return ([IntPtr]$Process.MainWindowHandle) }
  } while ([Environment]::TickCount -lt $deadline -and !$Process.HasExited)
  throw "Timed out waiting for Anvil main window"
}

function Capture-Window([IntPtr]$Hwnd, [string]$Path) {
  [AnvilSmokeWin32]::ShowWindow($Hwnd, 5) | Out-Null
  [AnvilSmokeWin32]::SetForegroundWindow($Hwnd) | Out-Null
  Start-Sleep -Milliseconds 250
  $rect = New-Object AnvilSmokeWin32+RECT
  if (![AnvilSmokeWin32]::GetWindowRect($Hwnd, [ref]$rect)) { throw "GetWindowRect failed" }
  $width = [Math]::Max(1, $rect.Right - $rect.Left)
  $height = [Math]::Max(1, $rect.Bottom - $rect.Top)
  $bmp = New-Object System.Drawing.Bitmap $width, $height
  $gfx = [System.Drawing.Graphics]::FromImage($bmp)
  try {
    try {
      $gfx.CopyFromScreen($rect.Left, $rect.Top, 0, 0, $bmp.Size)
    } catch {
      $hdc = $gfx.GetHdc()
      try {
        if (![AnvilSmokeWin32]::PrintWindow($Hwnd, $hdc, 2)) { throw }
      } finally {
        $gfx.ReleaseHdc($hdc)
      }
    }
    $bmp.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
  } finally {
    $gfx.Dispose()
    $bmp.Dispose()
  }
}

if ($PrepareRunDir) { Prepare-RunDirectory $RepoRoot }

if (!$NoKillExisting) {
  Get-Process anvil -ErrorAction SilentlyContinue | Stop-Process -Force
  Start-Sleep -Milliseconds 300
}

$runDir = Join-Path $RepoRoot ".run"
$exe = Join-Path $runDir "bin\anvil.exe"
if (!(Test-Path $exe)) {
  throw "Run-local executable not found: $exe. Re-run with -PrepareRunDir."
}

$fixture = New-ScrollFixture $TestProject
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$outDir = Join-Path $TestProject "anvil-d3d11-smoke-$stamp"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$statsFile = Join-Path $outDir "d3d11-stats.csv"

$oldUserProfile = $env:USERPROFILE
$oldRenderer = $env:ANVIL_RENDERER
$oldStats = $env:ANVIL_D3D11_STATS
$oldStatsFile = $env:ANVIL_D3D11_STATS_FILE
try {
  $env:USERPROFILE = $runDir
  $env:ANVIL_RENDERER = "d3d11"
  $env:ANVIL_D3D11_STATS = "1"
  $env:ANVIL_D3D11_STATS_FILE = $statsFile

  $proc = Start-Process -FilePath $exe -ArgumentList @($fixture) -WorkingDirectory $TestProject -PassThru
  $hwnd = Wait-MainWindow $proc
  Capture-Window $hwnd (Join-Path $outDir "00-open.png")

  for ($i = 1; $i -le $ScrollSteps; $i++) {
    [AnvilSmokeWin32]::SetForegroundWindow($hwnd) | Out-Null
    [AnvilSmokeWin32]::PostMessage($hwnd, 0x0100, [IntPtr]0x22, [IntPtr]0) | Out-Null
    [AnvilSmokeWin32]::PostMessage($hwnd, 0x0101, [IntPtr]0x22, [IntPtr]0) | Out-Null
    Start-Sleep -Milliseconds 180
    if ($i -eq 1 -or $i -eq $ScrollSteps -or ($i % 4) -eq 0) {
      Capture-Window $hwnd (Join-Path $outDir ("{0:D2}-scroll.png" -f $i))
    }
  }

  Start-Sleep -Milliseconds 500
  if (Test-Path $statsFile) {
    Get-Content -LiteralPath $statsFile -Head 8 | Out-Host
  } else {
    Write-Warning "Stats file was not created: $statsFile"
  }

  if (!$KeepOpen) {
    $proc.CloseMainWindow() | Out-Null
    if (!$proc.WaitForExit(3000)) { $proc.Kill() }
  }

  Write-Host "Smoke output: $outDir"
} finally {
  $env:USERPROFILE = $oldUserProfile
  $env:ANVIL_RENDERER = $oldRenderer
  $env:ANVIL_D3D11_STATS = $oldStats
  $env:ANVIL_D3D11_STATS_FILE = $oldStatsFile
}
