local common = require "core.common"
local core = require "core"
local Doc = require "core.doc"
local links = require "core.markdown.links"
local Project = require "core.project"
local test = require "core.test"
local vault_index = require "core.markdown.vault_index"
local rename_links = require "core.markdown.rename_links"

local function join_path(...)
  return table.concat({...}, PATHSEP)
end

local function write_file(path, content)
  local file, err = io.open(path, "wb")
  test.not_nil(file, err)
  file:write(content or "")
  file:close()
end

local function mkdirp(path)
  local ok, err = common.mkdirp(path)
  test.ok(ok, err)
end

local function temp_root(name)
  return join_path(USERDIR, name .. "-" .. system.get_process_id() .. "-" .. math.floor(system.get_time() * 1000000))
end

local function with_projects(projects, fn)
  local old_projects = core.projects
  core.projects = projects
  local ok, err = pcall(fn)
  core.projects = old_projects
  if not ok then error(err) end
end

local function wiki(text)
  return links.find_links(text, 1)[1]
end

local function normalized(path)
  return common.normalize_path(path)
end

test.describe("Markdown vault index", function()
  test.it("cooperatively builds a cold index and publishes readiness", function()
    local root = temp_root("markdown-vault-async")
    mkdirp(root)
    for i = 1, 70 do write_file(join_path(root, "Note" .. i .. ".md"), "# Note " .. i .. "\n") end
    local index = vault_index.get_index(root)
    local events = {}
    index:add_listener("test", function(_, reason) events[#events + 1] = reason end)
    test.equal(index:ensure("test"), false)
    test.equal(index.status, "indexing")
    local deadline = system.get_time() + 5
    while index.status ~= "ready" and system.get_time() < deadline do coroutine.yield(0.01) end
    test.equal(index.status, "ready")
    test.equal(index:note_count(), 70)
    test.same(events, { "indexing", "ready" })
    index:remove_listener("test")
    common.rm(root, true)
  end)

  test.it("reconciles filesystem changes while preserving open-Document overlays", function()
    local root = temp_root("markdown-vault-reconcile")
    mkdirp(root)
    local existing = join_path(root, "Existing.md")
    write_file(existing, "# Old\n")
    local index = vault_index.get_index(root):rebuild("reconcile-test")

    local added = join_path(root, "Added.md")
    write_file(added, "# Added\n")
    test.equal(index:reconcile_dir(root, "test-create"), true)
    test.equal(index:resolve(wiki("[[Added#Added]]"), existing).status, "resolved")

    write_file(added, "# Changed heading\nextra\n")
    test.equal(index:reconcile_dir(root, "test-modify"), true)
    test.equal(index:resolve(wiki("[[Added#Changed heading]]"), existing).status, "resolved")

    local nested = join_path(root, "nested")
    mkdirp(nested)
    write_file(join_path(nested, "Nested.md"), "# Nested\n")
    test.equal(index:reconcile_dir(root, "test-new-directory"), true)
    test.equal(index:resolve(wiki("[[nested/Nested]]"), existing).status, "resolved")

    local overlay_path = join_path(root, "Overlay.md")
    write_file(overlay_path, "# Disk\n")
    local overlay = Doc(overlay_path, overlay_path, true)
    overlay:insert(1, 1, "# Unsaved\n")
    index:track_doc(overlay)
    os.remove(overlay_path)
    index:reconcile_dir(root, "test-overlay-delete")
    test.equal(index:resolve(wiki("[[Overlay#Unsaved]]"), existing).status, "resolved")

    os.remove(existing)
    common.rm(nested, true)
    test.equal(index:reconcile_dir(root, "test-delete"), true)
    test.equal(index:resolve(wiki("[[Existing]]"), added).status, "missing")
    test.equal(index:resolve(wiki("[[nested/Nested]]"), added).status, "missing")
    test.equal(index:resolve(wiki("[[Overlay#Unsaved]]"), added).status, "resolved")

    index:on_doc_closed(overlay)
    common.rm(root, true)
  end)

  test.it("starts and stops filesystem watching with active consumers", function()
    local root = temp_root("markdown-vault-watch-lifecycle")
    mkdirp(root)
    local index = vault_index.get_index(root)
    test.equal(index:acquire("test-consumer"), true)
    test.not_nil(index.watcher)
    test.equal(index:acquire("test-consumer"), false)
    test.equal(index:release("test-consumer"), true)
    test.equal(index.watcher, nil)
    common.rm(root, true)
  end)

  test.it("bounds oversized cold-start notes with shallow entries", function()
    local root = temp_root("markdown-vault-large")
    mkdirp(root)
    write_file(join_path(root, "Large.md"), "# Heading\n" .. string.rep("prose ", 90000))
    local index = vault_index.get_index(root)
    index:ensure("test-large")
    local deadline = system.get_time() + 5
    while index.status ~= "ready" and system.get_time() < deadline do coroutine.yield(0.01) end
    test.equal(index.status, "ready")
    test.equal(index:resolve(wiki("[[Large]]"), join_path(root, "Source.md")).status, "resolved")
    test.equal(index:resolve(wiki("[[Large#Heading]]"), join_path(root, "Source.md")).status, "missing")
    common.rm(root, true)
  end)

  test.it("reconciles a tracked rename during cooperative scanning", function()
    local root1 = temp_root("markdown-vault-race-one")
    local root2 = temp_root("markdown-vault-race-two")
    mkdirp(root1)
    mkdirp(root2)
    for i = 1, 70 do write_file(join_path(root1, "Fill" .. i .. ".md"), "# Fill\n") end
    local old_path = join_path(root1, "Old.md")
    local new_path = join_path(root2, "New.md")
    write_file(old_path, "# Old\n")
    with_projects({ Project(root1), Project(root2) }, function()
      local index = vault_index.get_index(root1)
      local doc = Doc(old_path, old_path, true)
      doc:insert(1, 1, "# Unsaved\n")
      index:track_doc(doc)
      index:ensure("rename-race")
      coroutine.yield(0)
      os.remove(old_path)
      doc:set_filename(new_path, new_path)
      local deadline = system.get_time() + 5
      while index.status ~= "ready" and system.get_time() < deadline do coroutine.yield(0.01) end
      test.equal(index.status, "ready")
      test.equal(index:resolve(wiki("[[Old]]"), join_path(root1, "Source.md")).status, "missing")
    end)
    common.rm(root1, true)
    common.rm(root2, true)
  end)

  test.it("resolves note, heading, and block wikilinks", function()
    local root = temp_root("markdown-vault-index")
    mkdirp(root)
    write_file(join_path(root, "Note.md"), "# Heading\n\nText ^block-id\n")
    write_file(join_path(root, "Nested.md"), "# Parent\n## Child\n# Other\n## Child\n")
    write_file(join_path(root, "Source.md"), "source\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local result = index:resolve(wiki("[[Note]]"), join_path(root, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.kind, "note")
      test.equal(result.path, normalized(join_path(root, "Note.md")))

      result = index:resolve(wiki("[[Note#Heading]]"), join_path(root, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 1)

      result = index:resolve(wiki("[[Note#^block-id]]"), join_path(root, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 3)

      result = index:resolve(wiki("[[Nested#Parent#Child]]"), join_path(root, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 2)
      result = index:resolve(wiki("[[Nested#Other#Child]]"), join_path(root, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 4)

      result = index:resolve(wiki("[[#Heading]]"), join_path(root, "Note.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 1)
      result = index:resolve(wiki("[[^block-id]]"), join_path(root, "Note.md"))
      test.equal(result.status, "resolved")
      test.equal(result.line, 3)

      result = index:resolve(
        links.find_links("[download](Note.md?download#Heading)", 1)[1],
        join_path(root, "Source.md")
      )
      test.equal(result.status, "resolved")
      test.equal(result.line, 1)
    end)

    common.rm(root, true)
  end)

  test.it("provides deterministic note, alias, heading, block, and attachment completion states", function()
    local root = temp_root("markdown-vault-completion")
    mkdirp(join_path(root, "folder"))
    write_file(join_path(root, "Source.md"), "# Local Heading\n\ntext ^local-block\n")
    write_file(join_path(root, "Note.md"), "---\naliases: [Alias Name]\n---\n# Global Heading\n\ntext ^global-block\n")
    write_file(join_path(root, "folder", "Note.md"), "# Other\n")
    write_file(join_path(root, "image.png"), "png")
    local index = vault_index.get_index(root):rebuild("completion-test")
    local source = join_path(root, "Source.md")
    local function find(items, kind, target)
      for _, item in ipairs(items) do
        if item.kind == kind and item.target == target then return item end
      end
    end

    test.not_nil(find(index:completion_candidates("note", "alias", source), "alias", "Note.md|Alias Name"))
    test.not_nil(find(index:completion_candidates("note", "image", source), "attachment", "image.png"))
    test.not_nil(find(index:completion_candidates("current_heading", "local", source), "heading", "#Local Heading"))
    test.not_nil(find(index:completion_candidates("global_heading", "global", source), "heading", "Note.md#Global Heading"))
    test.not_nil(find(index:completion_candidates("current_block", "local", source), "block", "^local-block"))
    test.not_nil(find(index:completion_candidates("global_block", "global", source), "block", "Note.md#^global-block"))
    local notes = index:completion_candidates("note", "note", source)
    test.not_nil(find(notes, "note", "Note.md"))
    test.not_nil(find(notes, "note", "folder/Note"))

    test.equal(index:set_link_path_policy("root"), true)
    notes = index:completion_candidates("note", "note", source)
    test.not_nil(find(notes, "note", "Note"))
    test.not_nil(find(notes, "note", "folder/Note"))
    test.equal(index:resolve(wiki("[[Note]]"), source).path, normalized(join_path(root, "Note.md")))

    test.equal(index:set_link_path_policy("relative"), true)
    notes = index:completion_candidates("note", "note", join_path(root, "folder", "Source.md"))
    test.not_nil(find(notes, "note", "../Note"))
    test.not_nil(find(notes, "note", "./Note"))
    test.equal(index:set_link_path_policy("shortest_unique"), true)
    common.rm(root, true)
  end)

  test.it("resolves explicit project-relative and source-relative paths", function()
    local root = temp_root("markdown-vault-paths")
    mkdirp(join_path(root, "folder"))
    write_file(join_path(root, "folder", "Note.md"), "# Folder Note\n")
    write_file(join_path(root, "folder", "Other.markdown"), "# Other\n")
    write_file(join_path(root, "folder", "Source.md"), "source\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local project_relative = index:resolve(wiki("[[folder/Note]]"), join_path(root, "folder", "Source.md"))
      test.equal(project_relative.status, "resolved")
      test.equal(project_relative.path, normalized(join_path(root, "folder", "Note.md")))

      local source_relative = index:resolve(wiki("[[./Note]]"), join_path(root, "folder", "Source.md"))
      test.equal(source_relative.status, "resolved")
      test.equal(source_relative.path, normalized(join_path(root, "folder", "Note.md")))

      local alternate_extension = index:resolve(wiki("[[folder/Other]]"), join_path(root, "folder", "Source.md"))
      test.equal(alternate_extension.status, "resolved")
      test.equal(alternate_extension.path, normalized(join_path(root, "folder", "Other.markdown")))
    end)

    common.rm(root, true)
  end)

  test.it("resolves against the source note's owning Project", function()
    local root1 = temp_root("markdown-vault-project-one")
    local root2 = temp_root("markdown-vault-project-two")
    mkdirp(root1)
    mkdirp(root2)
    write_file(join_path(root1, "Note.md"), "# One\n")
    write_file(join_path(root2, "Note.md"), "# Two\n")
    write_file(join_path(root2, "Source.md"), "source\n")

    with_projects({ Project(root1), Project(root2) }, function()
      vault_index.get_index(root1):rebuild("test")
      vault_index.get_index(root2):rebuild("test")
      local result = vault_index.resolve(wiki("[[Note]]"), join_path(root2, "Source.md"))
      test.equal(result.status, "resolved")
      test.equal(result.path, normalized(join_path(root2, "Note.md")))
    end)

    common.rm(root1, true)
    common.rm(root2, true)
  end)

  test.it("reports ambiguous note names instead of choosing one", function()
    local root = temp_root("markdown-vault-ambiguous")
    mkdirp(join_path(root, "a"))
    mkdirp(join_path(root, "b"))
    write_file(join_path(root, "a", "Note.md"), "# A\n")
    write_file(join_path(root, "b", "Note.md"), "# B\n")
    write_file(join_path(root, "Source.md"), "source\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local result = index:resolve(wiki("[[Note]]"), join_path(root, "Source.md"))
      test.equal(result.status, "ambiguous")
      test.equal(#result.candidates, 2)
    end)

    common.rm(root, true)
  end)

  test.it("resolves attachments by explicit filename and rejects outside-vault absolutes", function()
    local root = temp_root("markdown-vault-attachments")
    local outside = temp_root("markdown-vault-outside")
    mkdirp(root)
    mkdirp(outside)
    write_file(join_path(root, "image.png"), "png")
    write_file(join_path(root, "Source.md"), "source\n")
    write_file(join_path(outside, "Other.md"), "# Other\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local missing = index:resolve(wiki("[[image]]"), join_path(root, "Source.md"))
      test.equal(missing.status, "missing")

      local attachment = index:resolve(wiki("[[image.png]]"), join_path(root, "Source.md"))
      test.equal(attachment.status, "resolved")
      test.equal(attachment.kind, "attachment")

      local external = index:resolve(wiki("[[" .. join_path(outside, "Other.md") .. "]]"), join_path(root, "Source.md"))
      test.equal(external.status, "external")
    end)

    common.rm(root, true)
    common.rm(outside, true)
  end)

  test.it("updates heading and block targets from tracked Document edits", function()
    local root = temp_root("markdown-vault-doc-update")
    mkdirp(root)
    local note_path = join_path(root, "Note.md")
    write_file(note_path, "# Old\n\nText ^old\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local doc = Doc(note_path, note_path, true)
      doc:insert(1, 1, "# New\n\nText ^new\n")
      index:track_doc(doc)

      local heading = index:resolve(wiki("[[Note#New]]"), note_path)
      test.equal(heading.status, "resolved")
      test.equal(heading.line, 1)
      local block = index:resolve(wiki("[[Note#^new]]"), note_path)
      test.equal(block.status, "resolved")
      test.equal(block.line, 3)

      doc:remove(1, 1, math.huge, math.huge)
      doc:insert(1, 1, "# New Heading\n\nText ^new\n")
      heading = index:resolve(wiki("[[Note#New Heading]]"), note_path)
      test.equal(heading.status, "resolved")
      local old = index:resolve(wiki("[[Note#New]]"), note_path)
      test.equal(old.status, "missing")
    end)

    common.rm(root, true)
  end)

  test.it("releases closed unsaved Document overlays", function()
    local root = temp_root("markdown-vault-doc-close")
    mkdirp(root)
    local ghost_path = join_path(root, "Ghost.md")
    local source_path = join_path(root, "Source.md")
    write_file(source_path, "source\n")
    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local doc = Doc(ghost_path, ghost_path, true)
      doc:insert(1, 1, "# Unsaved\n")
      index:track_doc(doc)
      test.equal(index:resolve(wiki("[[Ghost]]"), source_path).status, "resolved")
      doc:on_close()
      test.equal(index:resolve(wiki("[[Ghost]]"), source_path).status, "missing")
    end)
    common.rm(root, true)
  end)

  test.it("plans semantic target-only link edits for a note rename", function()
    local root = temp_root("markdown-vault-rename-plan")
    mkdirp(root)
    local old_path = join_path(root, "Old.md")
    local new_path = join_path(root, "Renamed.md")
    local ref_path = join_path(root, "Ref.md")
    write_file(old_path, "# Heading\n")
    write_file(ref_path, "[[Old#Heading|Alias]] ![[Old]] [old](Old.md#Heading) [[Old?mode#Heading]] `[[Old]]`\n")
    local index = vault_index.get_index(root):rebuild("rename-plan-test")
    local plan = test.not_nil(index:plan_note_rename(old_path, new_path))
    test.equal(#plan.files, 1)
    test.equal(plan.files[1].path, normalized(ref_path))
    test.equal(#plan.files[1].edits, 4)
    test.same({ plan.files[1].edits[1].text, plan.files[1].edits[2].text, plan.files[1].edits[3].text, plan.files[1].edits[4].text },
      { "Renamed#Heading", "Renamed", "Renamed.md#Heading", "Renamed?mode#Heading" })
    local applied, result = rename_links.apply(plan)
    test.equal(applied, true)
    test.same(result.applied, { normalized(ref_path) })
    local updated = test.not_nil(io.open(ref_path, "rb")); local updated_text = updated:read("*a"); updated:close()
    test.equal(updated_text,
      "[[Renamed#Heading|Alias]] ![[Renamed]] [old](Renamed.md#Heading) [[Renamed?mode#Heading]] `[[Old]]`\n")
    common.rm(root, true)
  end)

  test.it("publishes bounded note, heading, and block embed previews", function()
    local root = temp_root("markdown-vault-embed-preview")
    mkdirp(root)
    local note_path = join_path(root, "Note.md")
    write_file(note_path, "# Heading\nfirst\nsecond\n\n## Child\nchild text\n\nblock content ^block-id\n")
    local index = vault_index.get_index(root):rebuild("embed-preview-test")
    local entry = test.not_nil(index.notes_by_abs[common.path_compare_key(normalized(note_path))])
    test.same(entry.embed_preview, { "Heading", "first", "second" })
    test.same(entry.headings_by_slug.heading.embed_preview, { "first", "second" })
    test.same(entry.headings_by_slug.child.embed_preview, { "child text", "block content" })
    test.same(entry.blocks_by_id["block-id"].embed_preview, { "block content" })
    common.rm(root, true)
  end)

  test.it("indexes normalized frontmatter aliases and tags", function()
    local root = temp_root("markdown-vault-frontmatter")
    mkdirp(root)
    local note_path = join_path(root, "Note.md")
    write_file(note_path, "---\naliases: [One, 'Two']\ntags:\n  - project/anvil\n  - '#status/active'\ncategory: docs\n---\n# Note\n")
    local index = vault_index.get_index(root):rebuild("frontmatter-test")
    local entry = test.not_nil(index.notes_by_abs[common.path_compare_key(normalized(note_path))])
    test.same(entry.aliases, { "One", "Two" })
    test.same(entry.tags, { "project/anvil", "status/active" })
    test.equal(entry.frontmatter.category, "docs")
    common.rm(root, true)
  end)

  test.it("replaces stale aliases when re-indexing an existing file", function()
    local root = temp_root("markdown-vault-alias-update")
    mkdirp(root)
    local note_path = join_path(root, "Note.md")
    local source_path = join_path(root, "Source.md")
    write_file(source_path, "source\n")
    write_file(note_path, "---\naliases: [Old]\n---\n# Note\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      test.equal(index:resolve(wiki("[[Old]]"), source_path).status, "resolved")
      write_file(note_path, "---\naliases: [New]\n---\n# Note\n")
      test.equal(index:update_path(note_path), true)
      test.equal(index:resolve(wiki("[[Old]]"), source_path).status, "missing")
      test.equal(index:resolve(wiki("[[New]]"), source_path).status, "resolved")
    end)

    common.rm(root, true)
  end)

  test.it("returns external results for URL targets", function()
    local root = temp_root("markdown-vault-external-url")
    mkdirp(root)
    write_file(join_path(root, "Source.md"), "source\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local result = index:resolve(links.find_links("[Site](https://example.com/page.html)", 1)[1], join_path(root, "Source.md"))
      test.equal(result.status, "external")
      test.equal(result.path, "https://example.com/page.html")
    end)

    common.rm(root, true)
  end)

  test.it("updates tracked docs after filename changes", function()
    local root = temp_root("markdown-vault-rename")
    mkdirp(root)
    local old_path = join_path(root, "Old.md")
    local new_path = join_path(root, "New.md")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local doc = Doc(old_path, old_path, true)
      doc:insert(1, 1, "# Renamed\n")
      index:track_doc(doc)
      test.equal(index:resolve(wiki("[[Old]]"), old_path).status, "resolved")
      doc:set_filename(new_path, new_path)
      test.equal(index:resolve(wiki("[[Old]]"), new_path).status, "missing")
      test.equal(index:resolve(wiki("[[New]]"), new_path).status, "resolved")
    end)

    common.rm(root, true)
  end)

  test.it("retains an old disk note when an open Document is saved as a new path", function()
    local root = temp_root("markdown-vault-save-as")
    mkdirp(root)
    local old_path = join_path(root, "Old.md")
    local new_path = join_path(root, "New.md")
    write_file(old_path, "# Disk Original\n")
    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      local doc = Doc(old_path, old_path, true)
      doc:insert(1, 1, "# Open Overlay\n")
      index:track_doc(doc)
      doc:set_filename(new_path, new_path)
      test.equal(index:resolve(wiki("[[Old#Disk Original]]"), new_path).status, "resolved")
      test.equal(index:resolve(wiki("[[New#Open Overlay]]"), new_path).status, "resolved")
    end)
    common.rm(root, true)
  end)

  test.it("untracks old vault indexes when tracked docs move across roots", function()
    local root1 = temp_root("markdown-vault-rename-root-one")
    local root2 = temp_root("markdown-vault-rename-root-two")
    mkdirp(root1)
    mkdirp(root2)
    local old_path = join_path(root1, "Old.md")
    local new_path = join_path(root2, "New.md")
    local source_path = join_path(root1, "Source.md")
    write_file(source_path, "source\n")

    with_projects({ Project(root1), Project(root2) }, function()
      local old_index = vault_index.get_index(root1):rebuild("test")
      local new_index = vault_index.get_index(root2):rebuild("test")
      local doc = Doc(old_path, old_path, true)
      doc:insert(1, 1, "# Old\n")
      old_index:track_doc(doc)
      test.equal(old_index:resolve(wiki("[[Old]]"), source_path).status, "resolved")
      doc:set_filename(new_path, new_path)
      doc:insert(2, 1, "# New Heading\n")
      test.equal(old_index:resolve(wiki("[[New]]"), source_path).status, "missing")
      test.equal(new_index:resolve(wiki("[[New]]"), new_path).status, "resolved")
    end)

    common.rm(root1, true)
    common.rm(root2, true)
  end)

  test.it("updates after new file creation and deletion invalidation", function()
    local root = temp_root("markdown-vault-file-events")
    mkdirp(root)
    local note_path = join_path(root, "New.md")
    local source_path = join_path(root, "Source.md")
    write_file(source_path, "source\n")

    with_projects({ Project(root) }, function()
      local index = vault_index.get_index(root):rebuild("test")
      test.equal(index:resolve(wiki("[[New]]"), source_path).status, "missing")
      write_file(note_path, "# New\n")
      test.equal(index:update_path(note_path), true)
      test.equal(index:resolve(wiki("[[New]]"), source_path).status, "resolved")
      os.remove(note_path)
      test.equal(index:remove_path(note_path), true)
      test.equal(index:resolve(wiki("[[New]]"), source_path).status, "missing")
    end)

    common.rm(root, true)
  end)
end)
