local links = require "core.markdown.links"
local test = require "core.test"

test.describe("Markdown link parsing", function()
  test.it("parses wikilinks with aliases and exact ranges", function()
    local found = links.find_links("See [[Note#Heading|Alias]] now", 3)
    test.equal(#found, 1)
    test.equal(found[1].kind, "wiki")
    test.equal(found[1].source_line, 3)
    test.equal(found[1].source_col1, 5)
    test.equal(found[1].source_col2, 27)
    test.equal(found[1].raw_target, "Note#Heading")
    test.equal(found[1].path, "Note")
    test.equal(found[1].subtarget.type, "heading")
    test.equal(found[1].subtarget.text, "Heading")
    test.equal(found[1].alias, "Alias")
  end)

  test.it("parses current-note heading and block links", function()
    local heading = links.find_links("[[#Local Heading]]", 1)[1]
    test.equal(heading.path, "")
    test.equal(heading.subtarget.type, "heading")
    test.equal(heading.subtarget.text, "Local Heading")

    local block = links.find_links("[[^quote-of-the-day]]", 1)[1]
    test.equal(block.path, "")
    test.equal(block.subtarget.type, "block")
    test.equal(block.subtarget.id, "quote-of-the-day")
  end)

  test.it("parses embed resize syntax", function()
    local image = links.find_links("![[image.png|640x480]] and ![[icon.png|100]]", 1)
    test.equal(#image, 2)
    test.equal(image[1].kind, "embed")
    test.equal(image[1].is_embed, true)
    test.equal(image[1].path, "image.png")
    test.equal(image[1].resize.width, 640)
    test.equal(image[1].resize.height, 480)
    test.equal(image[2].resize.width, 100)
    test.equal(image[2].resize.height, nil)
  end)

  test.it("parses Markdown links and image resize syntax", function()
    local found = links.find_links("[Alias](target.md#Heading) ![Alt|100x145](image.png)", 7)
    test.equal(#found, 2)
    test.equal(found[1].kind, "markdown")
    test.equal(found[1].path, "target.md")
    test.equal(found[1].subtarget.type, "heading")
    test.equal(found[1].subtarget.text, "Heading")
    test.equal(found[1].alias, "Alias")
    test.equal(found[2].kind, "image")
    test.equal(found[2].alt, "Alt")
    test.equal(found[2].resize.width, 100)
    test.equal(found[2].resize.height, 145)
  end)
end)
